name: Daily Test Execution

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    # Schedule the job to run daily at midnight UTC
    - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # Install Google Chrome
    - uses: browser-actions/setup-chrome@v1
    - run: chrome --version

    # Run tests with Maven
    - name: Execute Tests with Maven
      run: mvn clean test --file pom.xml
