name: Daily Test Execution

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    # Schedule the job to run daily at midnight UTC
    - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # Install Google Chrome
    - name: Install Chrome
    - uses: browser-actions/setup-chrome@v1
    - run: chrome --version

    # Run tests with Maven
    - name: Execute Tests with Maven
      run: mvn clean test --file pom.xml

    # Optional: Upload the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
